const fs = require('fs');

function mc(correct, wrong1, wrong2, wrong3) {
  return [
    { text: String(correct).trim(), isCorrect: true },
    { text: String(wrong1).trim(), isCorrect: false },
    { text: String(wrong2).trim(), isCorrect: false },
    { text: String(wrong3).trim(), isCorrect: false }
  ];
}

function tf(correctIsTrue) {
  return [
    { text: "True", isCorrect: correctIsTrue },
    { text: "False", isCorrect: !correctIsTrue }
  ];
}

// Complete rich card definitions for all 129 cards
const cards = [
  // ==========================================
  // GRADE 7 EASY (11 cards)
  // ==========================================
  {
    qrId: "g7e01",
    grade: 7,
    difficulty: 1,
    category: "polygons-angles",
    title: "Interior Angle Formula",
    questionType: "multiple_choice",
    expectedAnswer: "(n - 2) * 180°",
    acceptableAnswers: ["(n-2)*180", "(n-2)180", "(n - 2) * 180°", "(n-2)180°", "(n-2)*180 deg"],
    problemText: "Which formula gives the sum of interior angles of a polygon with n sides?",
    answers: mc("(n - 2) * 180°", "n * 180°", "(n + 2) * 180°", "(n - 2) * 90°"),
    solution: "The sum of the interior angles of an n-sided polygon is given by S = (n - 2) × 180°."
  },
  {
    qrId: "g7e02",
    grade: 7,
    difficulty: 1,
    category: "polygons-angles",
    title: "Supplementary Angle Quest",
    questionType: "input",
    expectedAnswer: "105°",
    acceptableAnswers: ["105", "105°", "105 deg", "105 degrees"],
    problemText: "In the figure, ∠ABD and ∠CBD are supplementary angles. If m∠ABD = 75°, what is m∠CBD?",
    answers: mc("105°", "15°", "95°", "115°"),
    solution: "Supplementary angles add up to 180°. Therefore, m∠CBD = 180° - 75° = 105°."
  },
  {
    qrId: "g7e03",
    grade: 7,
    difficulty: 1,
    category: "fractions-rational",
    title: "Simple Interest Formula",
    questionType: "multiple_choice",
    expectedAnswer: "I = Prt",
    acceptableAnswers: ["I=Prt", "I = Prt", "Prt"],
    problemText: "Maria invested ₱10,000 in a savings account that earns simple interest at a rate of 5% per year for 2 years. Which formula should Maria use to calculate the simple interest I?",
    answers: mc("I = Prt", "I = P + r + t", "I = P(1 + r)^t", "I = P / (rt)"),
    solution: "Simple interest is calculated using I = Prt, where P is principal, r is the annual rate, and t is time in years."
  },
  {
    qrId: "g7e04",
    grade: 7,
    difficulty: 1,
    category: "fractions-rational",
    title: "Identifying Rational Numbers",
    questionType: "multiple_choice",
    expectedAnswer: "0.121212…",
    acceptableAnswers: ["0.121212…", "0.121212...", "0.121212", "4/33"],
    problemText: "Which of the following is a rational number?",
    answers: mc("0.121212…", "π", "100 / 0", "√5"),
    solution: "0.121212… is a repeating decimal equal to 4/33, which is rational because it is a quotient of two integers."
  },
  {
    qrId: "g7e05",
    grade: 7,
    difficulty: 1,
    category: "polygons-angles",
    title: "Regular Polygon Naming",
    questionType: "input",
    expectedAnswer: "Regular Hexagon",
    acceptableAnswers: ["regular hexagon", "hexagon", "a regular hexagon"],
    problemText: "What do you call a polygon with six equal sides and six equal interior angles?",
    answers: mc("Regular Hexagon", "Regular Pentagon", "Regular Octagon", "Regular Heptagon"),
    solution: "A 6-sided polygon with all equal sides and angles is a regular hexagon."
  },
  {
    qrId: "g7e06",
    grade: 7,
    difficulty: 1,
    category: "polygons-angles",
    title: "Complementary Angles Sum",
    questionType: "input",
    expectedAnswer: "90°",
    acceptableAnswers: ["90", "90°", "90 deg", "90 degrees"],
    problemText: "What is the sum of the measures of two complementary angles?",
    answers: mc("90°", "180°", "360°", "45°"),
    solution: "Two angles are complementary if the sum of their measures is 90°."
  },
  {
    qrId: "g7e07",
    grade: 7,
    difficulty: 1,
    category: "fractions-rational",
    title: "Definition of Discount",
    questionType: "true_false",
    expectedAnswer: "True",
    acceptableAnswers: ["true", "t", "yes"],
    problemText: "True or False: Discount is the amount deducted from the original price.",
    answers: tf(true),
    solution: "Discount is the amount deducted from the original or marked price."
  },
  {
    qrId: "g7e08",
    grade: 7,
    difficulty: 1,
    category: "fractions-rational",
    title: "Definition of Unit Rate",
    questionType: "true_false",
    expectedAnswer: "True",
    acceptableAnswers: ["true", "t", "yes"],
    problemText: "True or False: A unit rate is a rate that has 1 as its denominator.",
    answers: tf(true),
    solution: "A unit rate is a comparison to 1 unit of another measure."
  },
  {
    qrId: "g7e09",
    grade: 7,
    difficulty: 1,
    category: "fractions-rational",
    title: "Rational Number Condition",
    questionType: "input",
    expectedAnswer: "b ≠ 0",
    acceptableAnswers: ["b!=0", "b ≠ 0", "b is not equal to 0", "b not 0", "b=/=0"],
    problemText: "A rational number is a number that can be written as a fraction a/b, where a and b are integers and what condition holds for b?",
    answers: mc("b ≠ 0", "b = 0", "a = 0", "a > b"),
    solution: "Because division by zero is undefined, the denominator b must be nonzero (b ≠ 0)."
  },
  {
    qrId: "g7e10",
    grade: 7,
    difficulty: 1,
    category: "fractions-rational",
    title: "Number Line Direction",
    questionType: "input",
    expectedAnswer: "Left",
    acceptableAnswers: ["left", "to the left", "left of zero"],
    problemText: "On a standard horizontal number line, negative rational numbers are located to the _________ of zero.",
    answers: mc("Left", "Right", "Above", "Below"),
    solution: "Negative numbers are always positioned to the left of zero on a standard horizontal number line."
  },
  {
    qrId: "g7e11",
    grade: 7,
    difficulty: 1,
    category: "fractions-rational",
    title: "Nature of Zero",
    questionType: "true_false",
    expectedAnswer: "True",
    acceptableAnswers: ["true", "t", "yes"],
    problemText: "True or False: Zero is neither positive nor negative.",
    answers: tf(true),
    solution: "Zero is the neutral point between positive and negative numbers on the real number line."
  },

  // ==========================================
  // GRADE 7 AVERAGE (11 cards)
  // ==========================================
  {
    qrId: "g7a01",
    grade: 7,
    difficulty: 3,
    category: "polygons-angles",
    title: "Properties of Vertical Angles",
    questionType: "multiple_choice",
    expectedAnswer: "They are complementary.",
    acceptableAnswers: ["they are complementary", "complementary"],
    problemText: "Which of the following statements DOES NOT correctly describe vertical angles?",
    answers: mc("They are complementary.", "They are congruent.", "They are non-adjacent angles.", "They are formed from two intersecting lines."),
    solution: "Vertical angles are opposite angles formed by intersecting lines and are congruent, not necessarily complementary (summing to 90°)."
  },
  {
    qrId: "g7a02",
    grade: 7,
    difficulty: 3,
    category: "fractions-rational",
    title: "Recognizing Unit Rates",
    questionType: "multiple_choice",
    expectedAnswer: "Running at a speed of 24 kilometers per hour.",
    acceptableAnswers: ["running at a speed of 24 kilometers per hour.", "24 kilometers per hour", "24 km/h"],
    problemText: "Which of the following is expressed as a unit rate?",
    answers: mc("Running at a speed of 24 kilometers per hour.", "Buying 4 apples for ₱100.", "Paying ₱349 for 2 meals.", "Traveling 3 kilometers in 10 minutes."),
    solution: "24 kilometers per 1 hour has a denominator of 1 unit of time, which defines a unit rate."
  },
  {
    qrId: "g7a03",
    grade: 7,
    difficulty: 3,
    category: "fractions-rational",
    title: "Fraction to Decimal Conversion",
    questionType: "input",
    expectedAnswer: "0.375",
    acceptableAnswers: ["0.375", ".375", "3/8"],
    problemText: "Manuel is making a recipe that requires 3/8 cup of sugar. What is the decimal equivalent of 3/8?",
    answers: mc("0.375", "0.38", "0.625", "0.333"),
    solution: "Dividing 3 by 8: 3 ÷ 8 = 0.375."
  },
  {
    qrId: "g7a04",
    grade: 7,
    difficulty: 3,
    category: "fractions-rational",
    title: "Percentage to Fraction",
    questionType: "input",
    expectedAnswer: "1/2",
    acceptableAnswers: ["1/2", "0.5", "50/100", "2/4"],
    problemText: "What fraction in simplest form represents 50%?",
    answers: mc("1/2", "1/4", "1/5", "2/5"),
    solution: "50% = 50/100 = 1/2."
  },
  {
    qrId: "g7a05",
    grade: 7,
    difficulty: 3,
    category: "fractions-rational",
    title: "Earth's Water Percentage",
    questionType: "input",
    expectedAnswer: "0.97",
    acceptableAnswers: ["0.97", ".97", "97/100"],
    problemText: "The ocean holds 97% of the Earth’s water. What is 97% in decimal form?",
    answers: mc("0.97", "9.7", "0.097", "0.0097"),
    solution: "97% = 97 ÷ 100 = 0.97."
  },
  {
    qrId: "g7a06",
    grade: 7,
    difficulty: 3,
    category: "fractions-rational",
    title: "Decimal to Fraction Simplification",
    questionType: "input",
    expectedAnswer: "5/4",
    acceptableAnswers: ["5/4", "1 1/4", "1.25", "1 1/4"],
    problemText: "What is the equivalent fraction of 1.25 in simplest form?",
    answers: mc("5/4", "4/5", "12/5", "6/5"),
    solution: "1.25 = 125/100 = (125 ÷ 25) / (100 ÷ 25) = 5/4."
  },
  {
    qrId: "g7a07",
    grade: 7,
    difficulty: 3,
    category: "fractions-rational",
    title: "Simplest Form Definition",
    questionType: "multiple_choice",
    expectedAnswer: "The GCF of the numerator and denominator is 1.",
    acceptableAnswers: ["gcf of numerator and denominator is 1", "gcf is 1"],
    problemText: "What does it mean when a fraction is in simplest form?",
    answers: mc("The GCF of the numerator and denominator is 1.", "The numerator is always smaller than the denominator.", "The number is a decimal.", "The number is an integer."),
    solution: "A fraction is simplified when the Greatest Common Factor of its numerator and denominator is 1."
  },
  {
    qrId: "g7a08",
    grade: 7,
    difficulty: 3,
    category: "fractions-rational",
    title: "Comparing Unit Fractions",
    questionType: "input",
    expectedAnswer: "1/6",
    acceptableAnswers: ["1/6", "one sixth", "1 / 6"],
    problemText: "Which of the following fractions is the smallest: 1/2, 1/3, 1/5, or 1/6?",
    answers: mc("1/6", "1/2", "1/3", "1/5"),
    solution: "When numerators are equal to 1, larger denominators produce smaller fractions: 1/6 < 1/5 < 1/3 < 1/2."
  },
  {
    qrId: "g7a09",
    grade: 7,
    difficulty: 3,
    category: "fractions-rational",
    title: "Fraction on Number Line",
    questionType: "multiple_choice",
    expectedAnswer: "Between -1 and 0, closer to -1",
    acceptableAnswers: ["between -1 and 0, closer to -1"],
    problemText: "On a standard number line, where is -3/4 located relative to -1 and 0?",
    answers: mc("Between -1 and 0, closer to -1", "Between -1 and 0, closer to 0", "To the left of -1", "To the right of 0"),
    solution: "-3/4 = -0.75, which lies between 0 and -1, closer to -1."
  },
  {
    qrId: "g7a10",
    grade: 7,
    difficulty: 3,
    category: "polygons-angles",
    title: "Fountain Regular Pentagon",
    questionType: "input",
    expectedAnswer: "4m and 108°",
    acceptableAnswers: ["4m and 108°", "4 m and 108 degrees", "4m, 108°", "4, 108", "4m", "108°"],
    problemText: "Fountain Design: A fountain is a regular pentagon. One of the sides is 4 meters long, and one interior angle measures 108°. What are the lengths of the other sides and measures of the other interior angles?",
    answers: mc("All sides = 4 m, All interior angles = 108°", "All sides = 4 m, All interior angles = 72°", "All sides = 5 m, All interior angles = 108°", "All sides = 4 m, All interior angles = 120°"),
    solution: "In any regular polygon, all sides are congruent (4 m) and all interior angles are congruent (108°)."
  },
  {
    qrId: "g7a11",
    grade: 7,
    difficulty: 3,
    category: "polygons-angles",
    title: "Park Entrance Supplementary Angles",
    questionType: "input",
    expectedAnswer: "70°",
    acceptableAnswers: ["70", "70°", "70 deg", "70 degrees"],
    problemText: "Park Entrance: Two paths meet at the park entrance and form a pair of supplementary angles. If one angle measures 110°, what is the measure of the other angle?",
    answers: mc("70°", "80°", "90°", "110°"),
    solution: "Supplementary angles sum to 180°: 180° - 110° = 70°."
  },

  // ==========================================
  // GRADE 7 DIFFICULT (15 cards)
  // ==========================================
  {
    qrId: "g7d01",
    grade: 7,
    difficulty: 5,
    category: "polygons-angles",
    title: "Triangle Angle Sum Theorem",
    questionType: "multiple_choice",
    expectedAnswer: "42°, 58°, 80°",
    acceptableAnswers: ["42°, 58°, 80°", "42, 58, 80", "42,58,80"],
    problemText: "Jose will draw a triangle using a protractor. Which set of angle measures can form a triangle?",
    answers: mc("42°, 58°, 80°", "35°, 65°, 75°", "45°, 45°, 45°", "63°, 27°, 100°"),
    solution: "The interior angles of a triangle must sum to exactly 180°: 42° + 58° + 80° = 180°."
  },
  {
    qrId: "g7d02",
    grade: 7,
    difficulty: 5,
    category: "polygons-angles",
    title: "Classifying Non-Convex Polygons",
    questionType: "multiple_choice",
    expectedAnswer: "Irregular and non-convex polygons",
    acceptableAnswers: ["irregular and non-convex polygons", "irregular and non-convex", "concave"],
    problemText: "Which classification correctly describes polygons with unequal sides/angles that have at least one interior angle greater than 180°?",
    answers: mc("Irregular and non-convex polygons", "Irregular and convex polygons", "Regular and convex polygons", "Regular and non-convex polygons"),
    solution: "Polygons with unequal properties are irregular, and an interior angle > 180° makes them non-convex (concave)."
  },
  {
    qrId: "g7d03",
    grade: 7,
    difficulty: 5,
    category: "polygons-angles",
    title: "Intersecting Lines Angle Measures",
    questionType: "multiple_choice",
    expectedAnswer: "x = 104°, y = 76°, z = 104°",
    acceptableAnswers: ["x = 104°, y = 76°, z = 104°", "104, 76, 104"],
    problemText: "Two straight lines intersect. If one angle measures 76°, which statement gives the measures of the other three angles (x, y, z)?",
    answers: mc("x = 104°, y = 76°, z = 104°", "x = 104°, y = 104°, z = 76°", "x = 76°, y = 76°, z = 104°", "x = 76°, y = 104°, z = 76°"),
    solution: "Vertical angle y = 76°. Adjacent supplementary angles x = z = 180° - 76° = 104°."
  },
  {
    qrId: "g7d04",
    grade: 7,
    difficulty: 5,
    category: "fractions-rational",
    title: "Average Runner Speed",
    questionType: "input",
    expectedAnswer: "10 m/s",
    acceptableAnswers: ["10", "10 m/s", "10m/s", "10 meters per second", "10mps"],
    problemText: "A runner completes a 200-meter race in 20 seconds. What is the average speed in meters per second?",
    answers: mc("10 m/s", "20 m/s", "5 m/s", "15 m/s"),
    solution: "Speed = Distance ÷ Time = 200 m ÷ 20 s = 10 m/s."
  },
  {
    qrId: "g7d05",
    grade: 7,
    difficulty: 5,
    category: "fractions-rational",
    title: "Photocopy Machine Rate",
    questionType: "input",
    expectedAnswer: "200 papers",
    acceptableAnswers: ["200", "200 papers", "200 pages"],
    problemText: "If a machine produces 120 photocopy papers in 3 hours, how many papers will be produced in 5 hours at the same rate?",
    answers: mc("200 papers", "180 papers", "240 papers", "150 papers"),
    solution: "Rate = 120 ÷ 3 = 40 papers/hr. In 5 hours: 40 × 5 = 200 papers."
  },
  {
    qrId: "g7d06",
    grade: 7,
    difficulty: 5,
    category: "fractions-rational",
    title: "Speed Comparison",
    questionType: "input",
    expectedAnswer: "Car B at 60 km/h",
    acceptableAnswers: ["Car B", "Car B at 60 km/h", "Car B, 60 km/h", "Car B 60", "Car B, at 60 km/h", "60 km/h"],
    problemText: "Car A travels 200 km in 5 hours, while Car B travels 240 km in 4 hours. Which vehicle is faster, and what is its speed?",
    answers: mc("Car B, at 60 km/h", "Car A, at 40 km/h", "Car B, at 50 km/h", "Both have equal speed"),
    solution: "Speed A = 200/5 = 40 km/h. Speed B = 240/4 = 60 km/h. Car B is faster at 60 km/h."
  },
  {
    qrId: "g7d07",
    grade: 7,
    difficulty: 5,
    category: "fractions-rational",
    title: "Repeating Decimal to Fraction",
    questionType: "input",
    expectedAnswer: "2/3",
    acceptableAnswers: ["2/3", "2 / 3"],
    problemText: "What is the equivalent fraction of the repeating decimal 0.666… in simplest form?",
    answers: mc("2/3", "3/5", "6/10", "4/6"),
    solution: "Let x = 0.666…; 10x = 6.666…; 9x = 6 => x = 6/9 = 2/3."
  },
  {
    qrId: "g7d08",
    grade: 7,
    difficulty: 5,
    category: "fractions-rational",
    title: "Mixed Number to Improper Fraction",
    questionType: "input",
    expectedAnswer: "53/6",
    acceptableAnswers: ["53/6", "53 / 6"],
    problemText: "What is 8 5/6 expressed as an improper fraction?",
    answers: mc("53/6", "48/6", "45/6", "40/6"),
    solution: "(8 × 6 + 5) / 6 = (48 + 5) / 6 = 53/6."
  },
  {
    qrId: "g7d09",
    grade: 7,
    difficulty: 5,
    category: "fractions-rational",
    title: "Rational Numbers on Number Line",
    questionType: "multiple_choice",
    expectedAnswer: "-3.0 is left of 0, and 5.5 is right of 0",
    acceptableAnswers: ["-3.0 is left of 0, and 5.5 is right of 0", "A"],
    problemText: "Which statement correctly describes the plotting of rational numbers -3.0, 0, and 5.5 on a number line?",
    answers: mc("-3.0 is left of 0, and 5.5 is right of 0", "-3.0 is right of 0, and 5.5 is left of 0", "All three numbers lie to the right of 0", "0 is to the left of -3.0"),
    solution: "Negative rational numbers lie to the left of zero, and positive rational numbers lie to the right."
  },
  {
    qrId: "g7d10",
    grade: 7,
    difficulty: 5,
    category: "fractions-rational",
    title: "Locating 7/4 on Number Line",
    questionType: "input",
    expectedAnswer: "1.75",
    acceptableAnswers: ["1.75", "1 3/4", "7/4", "between 1 and 2, closer to 2", "Point A"],
    problemText: "What decimal value best locates the improper fraction 7/4 on a number line?",
    answers: mc("1.75 (between 1 and 2, closer to 2)", "1.25 (between 1 and 2, closer to 1)", "2.25 (between 2 and 3)", "0.75 (between 0 and 1)"),
    solution: "7/4 = 1.75, which lies between 1 and 2, closer to 2."
  },
  {
    qrId: "g7d11",
    grade: 7,
    difficulty: 5,
    category: "fractions-rational",
    title: "Ascending Order of Real Numbers",
    questionType: "input",
    expectedAnswer: "7/2, 5.6, 6",
    acceptableAnswers: ["7/2, 5.6, 6", "7/2, 5.6, 6.0", "3.5, 5.6, 6", "7/2,5.6,6"],
    problemText: "Arrange the following numbers in ascending order: 6, 7/2, 5.6",
    answers: mc("7/2, 5.6, 6", "5.6, 7/2, 6", "6, 5.6, 7/2", "7/2, 6, 5.6"),
    solution: "Convert 7/2 to 3.5. Comparing 3.5 < 5.6 < 6 gives: 7/2, 5.6, 6."
  },
  {
    qrId: "g7d12",
    grade: 7,
    difficulty: 5,
    category: "fractions-rational",
    title: "Electronics Commission Calculation",
    questionType: "input",
    expectedAnswer: "₱900",
    acceptableAnswers: ["900", "₱900", "P900", "Php 900", "900 pesos"],
    problemText: "Gregorio earns a 5% commission on electronics sales. He sold a tablet originally priced at ₱18,000. How much commission will Gregorio earn?",
    answers: mc("₱900", "₱1,800", "₱750", "₱1,200"),
    solution: "Commission = 5% of ₱18,000 = 0.05 × 18,000 = ₱900."
  },
  {
    qrId: "g7d13",
    grade: 7,
    difficulty: 5,
    category: "fractions-rational",
    title: "Discount Calculation",
    questionType: "input",
    expectedAnswer: "₱1,800",
    acceptableAnswers: ["1800", "1,800", "₱1800", "₱1,800", "P1800", "Php 1800"],
    problemText: "A tablet is originally priced at ₱18,000. Customers who pay in full receive a 10% discount. How much is the discount?",
    answers: mc("₱1,800", "₱900", "₱1,500", "₱2,000"),
    solution: "Discount = 10% of ₱18,000 = 0.10 × 18,000 = ₱1,800."
  },
  {
    qrId: "g7d14",
    grade: 7,
    difficulty: 5,
    category: "fractions-rational",
    title: "Running Trail Lap Time",
    questionType: "input",
    expectedAnswer: "200 seconds",
    acceptableAnswers: ["200", "200 seconds", "200 s", "200 sec"],
    problemText: "Running Trail: A park has a 400-meter running trail. A runner moves at a constant speed of 2 meters per second. How many seconds does the runner need to complete one lap (400 meters)?",
    answers: mc("200 seconds", "100 seconds", "400 seconds", "800 seconds"),
    solution: "Time = Distance ÷ Speed = 400 m ÷ 2 m/s = 200 seconds."
  },
  {
    qrId: "g7d15",
    grade: 7,
    difficulty: 5,
    category: "fractions-rational",
    title: "Park Distance Signs Ordering",
    questionType: "input",
    expectedAnswer: "0.1 km, 1/4 km, 1/2 km, 0.75 km",
    acceptableAnswers: ["0.1 km, 1/4 km, 1/2 km, 0.75 km", "0.1km, 1/4km, 1/2km, 0.75km", "0.1, 1/4, 1/2, 0.75", "0.1, 0.25, 0.5, 0.75"],
    problemText: "Park Entrance Signs: Distances to four areas are 0.1 km, 1/4 km, 0.75 km, and 1/2 km. Arrange the distances from nearest to farthest.",
    answers: mc("0.1 km, 1/4 km, 1/2 km, 0.75 km", "1/4 km, 0.1 km, 1/2 km, 0.75 km", "0.1 km, 1/2 km, 1/4 km, 0.75 km", "0.75 km, 1/2 km, 1/4 km, 0.1 km"),
    solution: "Convert all to decimals: 0.1 km, 0.25 km (1/4), 0.50 km (1/2), 0.75 km. Order: 0.1 km, 1/4 km, 1/2 km, 0.75 km."
  },

  // ==========================================
  // GRADE 8 EASY (13 cards)
  // ==========================================
  {
    qrId: "g8e01",
    grade: 8,
    difficulty: 1,
    category: "rational-algebraic-expressions",
    title: "Simplest Form of Rational Expressions",
    questionType: "multiple_choice",
    expectedAnswer: "When numerator and denominator have no common factors other than 1",
    acceptableAnswers: ["when numerator and denominator have no common factors other than 1", "no common factors other than 1"],
    problemText: "When is a rational algebraic expression considered to be in its simplest form?",
    answers: mc("When the numerator and denominator have no common factors other than 1.", "When the denominator is 1.", "When the numerator is a monomial.", "When both polynomials have degree 1."),
    solution: "A rational expression is in simplest form when numerator and denominator have no common factors other than ±1."
  },
  {
    qrId: "g8e02",
    grade: 8,
    difficulty: 1,
    category: "rational-algebraic-expressions",
    title: "Multiplying Rational Expressions First Step",
    questionType: "multiple_choice",
    expectedAnswer: "Factor all numerators and denominators completely.",
    acceptableAnswers: ["factor all numerators and denominators completely.", "factor completely", "factor"],
    problemText: "What is the first step before multiplying rational algebraic expressions containing polynomials?",
    answers: mc("Factor all numerators and denominators completely.", "Multiply numerators directly without factoring.", "Find a common denominator.", "Cancel terms that are not factors."),
    solution: "Factoring all numerators and denominators completely allows you to simplify common factors before multiplying."
  },
  {
    qrId: "g8e03",
    grade: 8,
    difficulty: 1,
    category: "rational-algebraic-expressions",
    title: "Product of Monomial Fractions",
    questionType: "input",
    expectedAnswer: "6/(xy)",
    acceptableAnswers: ["6/(xy)", "6/xy", "6 / (xy)", "6 / xy"],
    problemText: "What is the product of the expression (2/x) * (3/y)?",
    answers: mc("6 / (xy)", "5 / (x + y)", "6 / (x + y)", "5 / (xy)"),
    solution: "Multiply numerators and denominators: (2 * 3) / (x * y) = 6 / (xy)."
  },
  {
    qrId: "g8e04",
    grade: 8,
    difficulty: 1,
    category: "rational-algebraic-expressions",
    title: "Reciprocal of Rational Expression",
    questionType: "input",
    expectedAnswer: "(x + 5)/(x - 3)",
    acceptableAnswers: ["(x+5)/(x-3)", "(x + 5)/(x - 3)", "(x+5) / (x-3)"],
    problemText: "What is the reciprocal (multiplicative inverse) of the rational expression (x - 3)/(x + 5)?",
    answers: mc("(x + 5) / (x - 3)", "(x - 3) / (x + 5)", "-(x - 3) / (x + 5)", "(x - 5) / (x + 3)"),
    solution: "The reciprocal of A/B is B/A: the reciprocal of (x - 3)/(x + 5) is (x + 5)/(x - 3)."
  },
  {
    qrId: "g8e05",
    grade: 8,
    difficulty: 1,
    category: "rational-algebraic-expressions",
    title: "Division Process for Rational Expressions",
    questionType: "multiple_choice",
    expectedAnswer: "(A/B) * (D/C)",
    acceptableAnswers: ["(A/B) * (D/C)", "A/B * D/C", "A/B * (D/C)", "B"],
    problemText: "Which of the following describes the correct process for dividing two rational algebraic expressions: (A/B) ÷ (C/D)?",
    answers: mc("(A/B) * (D/C)", "(A/B) * (C/D)", "(B/A) * (C/D)", "(B/A) * (D/C)"),
    solution: "Dividing by a fraction is equivalent to multiplying by its reciprocal: (A/B) ÷ (C/D) = (A/B) * (D/C)."
  },
  {
    qrId: "g8e06",
    grade: 8,
    difficulty: 1,
    category: "special-products-factoring",
    title: "GCF of Polynomial",
    questionType: "input",
    expectedAnswer: "4x",
    acceptableAnswers: ["4x", "4*x", "4 x"],
    problemText: "To factor the polynomial 8x² - 12x, what is the greatest common factor (GCF) of the terms?",
    answers: mc("4x", "4", "2x", "8x"),
    solution: "GCF of coefficients 8 and 12 is 4, and common variable factor is x: GCF = 4x."
  },
  {
    qrId: "g8e07",
    grade: 8,
    difficulty: 1,
    category: "special-products-factoring",
    title: "Difference of Two Squares Factors",
    questionType: "input",
    expectedAnswer: "Conjugate binomials",
    acceptableAnswers: ["conjugate", "conjugate binomials", "sum and difference", "conjugates"],
    problemText: "The factors of the difference of two squares (a² - b²) are always a pair of __________.",
    answers: mc("Conjugate binomials (a - b)(a + b)", "Identical binomials (a - b)(a - b)", "Monomials", "Trinomials"),
    solution: "a² - b² factors into conjugate binomials: (a - b)(a + b)."
  },
  {
    qrId: "g8e08",
    grade: 8,
    difficulty: 1,
    category: "special-products-factoring",
    title: "Perfect Square Trinomial Factoring",
    questionType: "input",
    expectedAnswer: "Square of a binomial",
    acceptableAnswers: ["square", "square of a binomial", "binomial square"],
    problemText: "A perfect square trinomial (a² + 2ab + b²) always factors into the ______ of a binomial.",
    answers: mc("Square of a binomial (a + b)²", "Difference of squares", "Product of conjugates", "Cube of a binomial"),
    solution: "a² + 2ab + b² = (a + b)², which is the square of a binomial."
  },
  {
    qrId: "g8e09",
    grade: 8,
    difficulty: 1,
    category: "special-products-factoring",
    title: "Product of Sum and Difference",
    questionType: "input",
    expectedAnswer: "x² - 16",
    acceptableAnswers: ["x^2 - 16", "x² - 16", "x^2-16", "x²-16"],
    problemText: "What is the product of (x + 4)(x - 4)?",
    answers: mc("x² - 16", "x² + 16", "x² - 8x - 16", "x² + 8x + 16"),
    solution: "(x + 4)(x - 4) = x² - 4² = x² - 16."
  },
  {
    qrId: "g8e10",
    grade: 8,
    difficulty: 1,
    category: "special-products-factoring",
    title: "Square of Binomial Expansion",
    questionType: "input",
    expectedAnswer: "x² + 10x + 25",
    acceptableAnswers: ["x^2 + 10x + 25", "x² + 10x + 25", "x^2+10x+25", "x²+10x+25"],
    problemText: "Expand the square of a binomial: (x + 5)²",
    answers: mc("x² + 10x + 25", "x² + 25", "x² + 5x + 25", "x² + 10x + 10"),
    solution: "(x + 5)² = x² + 2(5)(x) + 5² = x² + 10x + 25."
  },
  {
    qrId: "g8e11",
    grade: 8,
    difficulty: 1,
    category: "special-products-factoring",
    title: "Factoring Simple Trinomials",
    questionType: "input",
    expectedAnswer: "(x + 2)(x + 3)",
    acceptableAnswers: ["(x+2)(x+3)", "(x + 2)(x + 3)", "(x+3)(x+2)", "(x + 3)(x + 2)"],
    problemText: "What are the factors of x² + 5x + 6?",
    answers: mc("(x + 2)(x + 3)", "(x + 1)(x + 6)", "(x - 2)(x - 3)", "(x - 1)(x - 6)"),
    solution: "Find numbers that multiply to 6 and add to 5: 2 and 3 => (x + 2)(x + 3)."
  },
  {
    qrId: "g8e12",
    grade: 8,
    difficulty: 1,
    category: "special-products-factoring",
    title: "Factoring Difference of Squares",
    questionType: "input",
    expectedAnswer: "(x - 7)(x + 7)",
    acceptableAnswers: ["(x-7)(x+7)", "(x - 7)(x + 7)", "(x+7)(x-7)", "(x + 7)(x - 7)"],
    problemText: "What is the factored form of the difference of squares: x² - 49?",
    answers: mc("(x - 7)(x + 7)", "(x - 7)²", "(x + 7)²", "(x - 49)(x + 1)"),
    solution: "x² - 49 = x² - 7² = (x - 7)(x + 7)."
  },
  {
    qrId: "g8e13",
    grade: 8,
    difficulty: 1,
    category: "rational-algebraic-expressions",
    title: "Simplifying Rational Expressions",
    questionType: "input",
    expectedAnswer: "x + 2",
    acceptableAnswers: ["x + 2", "x+2", "(x+2)"],
    problemText: "Simplify the rational expression: (3x + 6) / 3",
    answers: mc("x + 2", "x + 6", "3x + 2", "x + 3"),
    solution: "Factor numerator: 3(x + 2) / 3 = x + 2."
  },

  // ==========================================
  // GRADE 8 AVERAGE (8 cards)
  // ==========================================
  {
    qrId: "g8a01",
    grade: 8,
    difficulty: 3,
    category: "special-products-factoring",
    title: "Property in Multiplying Polynomials",
    questionType: "input",
    expectedAnswer: "Distributive Property",
    acceptableAnswers: ["distributive property", "distributive", "the distributive property"],
    problemText: "What algebraic property will you use to multiply 3x(2x + 5)?",
    answers: mc("Distributive Property", "Associative Property", "Commutative Property", "Identity Property"),
    solution: "The Distributive Property a(b + c) = ab + ac distributes 3x to both 2x and 5."
  },
  {
    qrId: "g8a02",
    grade: 8,
    difficulty: 3,
    category: "special-products-factoring",
    title: "Identifying Non-Special Products",
    questionType: "multiple_choice",
    expectedAnswer: "(x + 4)(x - 3)",
    acceptableAnswers: ["(x + 4)(x - 3)", "(x+4)(x-3)", "C"],
    problemText: "Which of the following expression pairs is NOT an example of a special product?",
    answers: mc("(x + 4)(x - 3)", "(x + 6)(x - 6)", "(3x + 2)²", "(2x - 5)(2x + 5)"),
    solution: "(x + 4)(x - 3) gives a general trinomial x² + x - 12, unlike differences of squares or perfect squares."
  },
  {
    qrId: "g8a03",
    grade: 8,
    difficulty: 3,
    category: "special-products-factoring",
    title: "Area of Square with Binomial Side",
    questionType: "input",
    expectedAnswer: "4x² + 12x + 9",
    acceptableAnswers: ["4x^2 + 12x + 9", "4x² + 12x + 9", "4x^2+12x+9", "4x²+12x+9"],
    problemText: "What is the area of a square whose side length is (2x + 3)?",
    answers: mc("4x² + 12x + 9", "4x² + 9", "4x² + 6x + 9", "2x² + 6x + 9"),
    solution: "Area = (2x + 3)² = (2x)² + 2(2x)(3) + 3² = 4x² + 12x + 9."
  },
  {
    qrId: "g8a04",
    grade: 8,
    difficulty: 3,
    category: "rational-algebraic-expressions",
    title: "Multiplying Reciprocal Fractions",
    questionType: "input",
    expectedAnswer: "1",
    acceptableAnswers: ["1", "one"],
    problemText: "Simplify the product: ((x - 2) / (x + 3)) * ((x + 3) / (x - 2))",
    answers: mc("1", "0", "(x - 2) / (x + 3)", "(x + 3) / (x - 2)"),
    solution: "All terms in numerator and denominator cancel: ((x - 2)(x + 3)) / ((x + 3)(x - 2)) = 1."
  },
  {
    qrId: "g8a05",
    grade: 8,
    difficulty: 3,
    category: "rational-algebraic-expressions",
    title: "Dividing Monomial Algebraic Fractions",
    questionType: "input",
    expectedAnswer: "6",
    acceptableAnswers: ["6", "six"],
    problemText: "Perform the division: (4x / 5) ÷ (2x / 15)",
    answers: mc("6", "6x", "8x² / 75", "3/2"),
    solution: "(4x / 5) * (15 / 2x) = 60x / 10x = 6."
  },
  {
    qrId: "g8a06",
    grade: 8,
    difficulty: 3,
    category: "special-products-factoring",
    title: "Completing Perfect Square Trinomial",
    questionType: "input",
    expectedAnswer: "16",
    acceptableAnswers: ["16", "sixteen"],
    problemText: "What is the missing term to make x² + 8x + ___ a perfect square trinomial?",
    answers: mc("16", "8", "64", "4"),
    solution: "Take half the middle coefficient squared: (8 / 2)² = 4² = 16."
  },
  {
    qrId: "g8a07",
    grade: 8,
    difficulty: 3,
    category: "special-products-factoring",
    title: "Complete Factoring of Trinomial",
    questionType: "input",
    expectedAnswer: "2(x + 2)(x + 3)",
    acceptableAnswers: ["2(x+2)(x+3)", "2(x + 2)(x + 3)", "2(x+3)(x+2)", "2(x + 3)(x + 2)"],
    problemText: "Factor completely: 2x² + 10x + 12",
    answers: mc("2(x + 2)(x + 3)", "2(x + 1)(x + 6)", "(2x + 4)(x + 3)", "(x + 2)(2x + 6)"),
    solution: "Factor out GCF 2: 2(x² + 5x + 6) = 2(x + 2)(x + 3)."
  },
  {
    qrId: "g8a08",
    grade: 8,
    difficulty: 3,
    category: "rational-algebraic-expressions",
    title: "Simplifying Rational Fraction with Difference of Squares",
    questionType: "input",
    expectedAnswer: "x + 4",
    acceptableAnswers: ["x + 4", "x+4", "(x+4)"],
    problemText: "Simplify the rational expression: (x² - 16) / (x - 4)",
    answers: mc("x + 4", "x - 4", "x + 16", "4"),
    solution: "Factor numerator as (x - 4)(x + 4). Cancel (x - 4): result is x + 4."
  },

  // ==========================================
  // GRADE 8 DIFFICULT (12 cards)
  // ==========================================
  {
    qrId: "g8d01",
    grade: 8,
    difficulty: 5,
    category: "special-products-factoring",
    title: "Expanding Monomial by Binomial",
    questionType: "input",
    expectedAnswer: "6x² + 15x",
    acceptableAnswers: ["6x^2 + 15x", "6x² + 15x", "6x^2+15x", "6x²+15x"],
    problemText: "What is the product of 3x(2x + 5)?",
    answers: mc("6x² + 15x", "6x² + 5", "5x² + 15x", "6x + 15"),
    solution: "Distribute 3x: 3x(2x) + 3x(5) = 6x² + 15x."
  },
  {
    qrId: "g8d02",
    grade: 8,
    difficulty: 5,
    category: "special-products-factoring",
    title: "Rectangular Board Area Claim",
    questionType: "input",
    expectedAnswer: "No, the correct area is x² - 49",
    acceptableAnswers: ["no, the correct area is x² - 49", "no", "x² - 49", "x^2 - 49", "x^2-49", "x²-49"],
    problemText: "A rectangular bulletin board has length (x + 7) m and width (x - 7) m. A student claims the area is x² + 49. Is the student correct? Why?",
    answers: mc("No, the correct area is x² - 49.", "Yes, the calculation is correct.", "No, the correct area is x² - 14x + 49.", "No, the correct area is x² + 14x - 49."),
    solution: "Area = (x + 7)(x - 7) = x² - 49 (difference of two squares). The student's sign was incorrect."
  },
  {
    qrId: "g8d03",
    grade: 8,
    difficulty: 5,
    category: "rational-algebraic-expressions",
    title: "Multiplying Complex Rational Expressions",
    questionType: "input",
    expectedAnswer: "x - 3",
    acceptableAnswers: ["x - 3", "x-3", "(x-3)"],
    problemText: "Simplify: ((x² - 9) / (x + 2)) * ((x + 2) / (x + 3))",
    answers: mc("x - 3", "x + 3", "(x - 3) / (x + 2)", "1"),
    solution: "Factor x² - 9 = (x - 3)(x + 3). Cancel common factors (x + 2) and (x + 3) to get x - 3."
  },
  {
    qrId: "g8d04",
    grade: 8,
    difficulty: 5,
    category: "rational-algebraic-expressions",
    title: "Dividing Complex Rational Expressions",
    questionType: "input",
    expectedAnswer: "x + 2",
    acceptableAnswers: ["x + 2", "x+2", "(x+2)"],
    problemText: "Divide and simplify: ((x² - 4) / (x + 1)) ÷ ((x - 2) / (x + 1))",
    answers: mc("x + 2", "x - 2", "(x + 2) / (x + 1)", "1"),
    solution: "Multiply by reciprocal: ((x - 2)(x + 2) / (x + 1)) * ((x + 1) / (x - 2)) = x + 2."
  },
  {
    qrId: "g8d05",
    grade: 8,
    difficulty: 5,
    category: "special-products-factoring",
    title: "Factoring Binomial Difference",
    questionType: "input",
    expectedAnswer: "3(x - 3)(x + 3)",
    acceptableAnswers: ["3(x-3)(x+3)", "3(x - 3)(x + 3)", "3(x+3)(x-3)", "3(x + 3)(x - 3)"],
    problemText: "Factor completely: 3x² - 27",
    answers: mc("3(x - 3)(x + 3)", "3(x - 9)", "(3x - 9)(x + 3)", "3(x - 3)²"),
    solution: "Factor out 3: 3(x² - 9) = 3(x - 3)(x + 3)."
  },
  {
    qrId: "g8d06",
    grade: 8,
    difficulty: 5,
    category: "special-products-factoring",
    title: "FOIL Binomial Product",
    questionType: "input",
    expectedAnswer: "6x² - x - 12",
    acceptableAnswers: ["6x^2 - x - 12", "6x² - x - 12", "6x^2-x-12", "6x²-x-12"],
    problemText: "What is the product of (2x - 3)(3x + 4)?",
    answers: mc("6x² - x - 12", "6x² + x - 12", "6x² - 12", "6x² + 17x - 12"),
    solution: "FOIL: (2x)(3x) + (2x)(4) + (-3)(3x) + (-3)(4) = 6x² + 8x - 9x - 12 = 6x² - x - 12."
  },
  {
    qrId: "g8d07",
    grade: 8,
    difficulty: 5,
    category: "rational-algebraic-expressions",
    title: "Rational Expression Simplification",
    questionType: "input",
    expectedAnswer: "(x + 3)/(x - 4)",
    acceptableAnswers: ["(x+3)/(x-4)", "(x + 3)/(x - 4)", "(x+3) / (x-4)"],
    problemText: "Simplify: (x² + 7x + 12) / (x² - 16)",
    answers: mc("(x + 3) / (x - 4)", "(x + 4) / (x - 4)", "(x + 3) / (x + 4)", "(x - 3) / (x - 4)"),
    solution: "Factor: ((x + 3)(x + 4)) / ((x - 4)(x + 4)) = (x + 3) / (x - 4)."
  },
  {
    qrId: "g8d08",
    grade: 8,
    difficulty: 5,
    category: "special-products-factoring",
    title: "Garden Area Modification",
    questionType: "input",
    expectedAnswer: "9 square meters less",
    acceptableAnswers: ["9", "9 sq m", "9 sq meters", "9 m²", "9 square meters less", "9 less", "-9"],
    problemText: "A square garden with side length x is extended by 3 m on one side and reduced by 3 m on the other. What is the difference between the original and new area?",
    answers: mc("9 square meters less", "9 square meters more", "No difference", "6 square meters less"),
    solution: "Original = x²; New = (x + 3)(x - 3) = x² - 9. The new area is 9 m² less."
  },
  {
    qrId: "g8d09",
    grade: 8,
    difficulty: 5,
    category: "rational-algebraic-expressions",
    title: "Adding Fractions with Like Denominators",
    questionType: "input",
    expectedAnswer: "5/(x - 1)",
    acceptableAnswers: ["5/(x-1)", "5/(x - 1)", "5 / (x-1)"],
    problemText: "Simplify: (2 / (x - 1)) + (3 / (x - 1))",
    answers: mc("5 / (x - 1)", "5 / (2x - 2)", "6 / (x - 1)", "5 / (x - 1)²"),
    solution: "Combine numerators over the common denominator: (2 + 3) / (x - 1) = 5 / (x - 1)."
  },
  {
    qrId: "g8d10",
    grade: 8,
    difficulty: 5,
    category: "special-products-factoring",
    title: "Finding Dimensions from Area",
    questionType: "input",
    expectedAnswer: "(x + 4) and (x + 5)",
    acceptableAnswers: ["(x+4) and (x+5)", "(x + 4) and (x + 5)", "(x+4), (x+5)", "(x+4)(x+5)"],
    problemText: "What are the dimensions of a rectangle with area x² + 9x + 20?",
    answers: mc("(x + 4) and (x + 5)", "(x + 2) and (x + 10)", "(x + 1) and (x + 20)", "(x - 4) and (x - 5)"),
    solution: "Factor x² + 9x + 20 into (x + 4)(x + 5)."
  },
  {
    qrId: "g8d11",
    grade: 8,
    difficulty: 5,
    category: "rational-algebraic-expressions",
    title: "Undefined Rational Expression Value",
    questionType: "input",
    expectedAnswer: "x = 7",
    acceptableAnswers: ["7", "x = 7", "x=7"],
    problemText: "For what value of x is the expression (x + 5) / (x - 7) undefined?",
    answers: mc("x = 7", "x = -5", "x = 0", "x = -7"),
    solution: "Set denominator to zero: x - 7 = 0 => x = 7."
  },
  {
    qrId: "g8d12",
    grade: 8,
    difficulty: 5,
    category: "special-products-factoring",
    title: "Factoring by Grouping",
    questionType: "input",
    expectedAnswer: "(x + 2)(x² + 3)",
    acceptableAnswers: ["(x+2)(x^2+3)", "(x + 2)(x² + 3)", "(x^2+3)(x+2)", "(x² + 3)(x + 2)"],
    problemText: "Factor completely by grouping: x³ + 2x² + 3x + 6",
    answers: mc("(x + 2)(x² + 3)", "(x + 3)(x² + 2)", "(x - 2)(x² + 3)", "(x + 2)(x + 3)"),
    solution: "Group: x²(x + 2) + 3(x + 2) = (x + 2)(x² + 3)."
  },

  // ==========================================
  // GRADE 9 EASY (15 cards)
  // ==========================================
  {
    qrId: "g9e01",
    grade: 9,
    difficulty: 1,
    category: "linear-equations",
    title: "Finding Slope from Equation",
    questionType: "input",
    expectedAnswer: "3",
    acceptableAnswers: ["3", "m = 3", "m=3"],
    problemText: "What is the slope of the line represented by the equation y = 3x - 5?",
    answers: mc("m = 3", "m = -5", "m = -3", "m = 5"),
    solution: "In slope-intercept form y = mx + b, slope m = 3."
  },
  {
    qrId: "g9e02",
    grade: 9,
    difficulty: 1,
    category: "linear-equations",
    title: "Finding Y-Intercept Ordered Pair",
    questionType: "input",
    expectedAnswer: "(0, 7)",
    acceptableAnswers: ["(0, 7)", "(0,7)", "0,7", "7", "y = 7"],
    problemText: "What ordered pair represents the y-intercept of the line y = 2x + 7?",
    answers: mc("(0, 7)", "(7, 0)", "(0, 2)", "(2, 7)"),
    solution: "At x = 0, y = 2(0) + 7 = 7, giving the ordered pair (0, 7)."
  },
  {
    qrId: "g9e03",
    grade: 9,
    difficulty: 1,
    category: "linear-equations",
    title: "Slope of Horizontal Line",
    questionType: "input",
    expectedAnswer: "0",
    acceptableAnswers: ["0", "zero", "m = 0"],
    problemText: "What is the slope of any horizontal line?",
    answers: mc("0", "1", "Undefined", "-1"),
    solution: "Horizontal lines have a vertical change (rise) of 0, so slope m = 0."
  },
  {
    qrId: "g9e04",
    grade: 9,
    difficulty: 1,
    category: "linear-equations",
    title: "Slope of Vertical Line",
    questionType: "input",
    expectedAnswer: "Undefined",
    acceptableAnswers: ["undefined", "no slope"],
    problemText: "What is the slope of any vertical line?",
    answers: mc("Undefined", "0", "1", "Infinity"),
    solution: "Vertical lines have a horizontal change (run) of 0; dividing by 0 makes the slope undefined."
  },
  {
    qrId: "g9e05",
    grade: 9,
    difficulty: 1,
    category: "linear-equations",
    title: "Slope-Intercept Form Form",
    questionType: "multiple_choice",
    expectedAnswer: "y = mx + b",
    acceptableAnswers: ["y = mx + b", "y=mx+b"],
    problemText: "Which form represents the slope-intercept form of a linear equation?",
    answers: mc("y = mx + b", "Ax + By = C", "y - y₁ = m(x - x₁)", "x/a + y/b = 1"),
    solution: "y = mx + b is the standard slope-intercept form."
  },
  {
    qrId: "g9e06",
    grade: 9,
    difficulty: 1,
    category: "quadrilaterals-geometry",
    title: "Definition of Parallelogram",
    questionType: "input",
    expectedAnswer: "Parallelogram",
    acceptableAnswers: ["parallelogram", "a parallelogram"],
    problemText: "Which quadrilateral has both pairs of opposite sides parallel and equal in length?",
    answers: mc("Parallelogram", "Trapezoid", "Kite", "Triangle"),
    solution: "A parallelogram is defined by having two pairs of parallel opposite sides."
  },
  {
    qrId: "g9e07",
    grade: 9,
    difficulty: 1,
    category: "quadrilaterals-geometry",
    title: "Consecutive Angles in Parallelogram",
    questionType: "input",
    expectedAnswer: "Supplementary (sum = 180°)",
    acceptableAnswers: ["supplementary", "180", "180°", "sum to 180"],
    problemText: "In any parallelogram, consecutive angles are always:",
    answers: mc("Supplementary (sum = 180°)", "Complementary (sum = 90°)", "Congruent (equal)", "Right angles"),
    solution: "Consecutive angles lie between parallel lines and are supplementary (sum = 180°)."
  },
  {
    qrId: "g9e08",
    grade: 9,
    difficulty: 1,
    category: "quadrilaterals-geometry",
    title: "Opposite Angles in Parallelogram",
    questionType: "input",
    expectedAnswer: "Congruent (equal)",
    acceptableAnswers: ["congruent", "equal", "congruent (equal)"],
    problemText: "In any parallelogram, opposite angles are always:",
    answers: mc("Congruent (equal)", "Supplementary", "Complementary", "Acute"),
    solution: "Opposite angles in every parallelogram are congruent (equal in measure)."
  },
  {
    qrId: "g9e09",
    grade: 9,
    difficulty: 1,
    category: "quadrilaterals-geometry",
    title: "Equiangular Parallelogram",
    questionType: "input",
    expectedAnswer: "Rectangle",
    acceptableAnswers: ["rectangle", "a rectangle"],
    problemText: "A parallelogram with four right angles is a:",
    answers: mc("Rectangle", "Rhombus", "Trapezoid", "Kite"),
    solution: "An equiangular parallelogram has four 90° angles and is called a rectangle."
  },
  {
    qrId: "g9e10",
    grade: 9,
    difficulty: 1,
    category: "quadrilaterals-geometry",
    title: "Equilateral Parallelogram",
    questionType: "input",
    expectedAnswer: "Rhombus",
    acceptableAnswers: ["rhombus", "a rhombus"],
    problemText: "A parallelogram with four congruent (equal) sides is a:",
    answers: mc("Rhombus", "Rectangle", "Trapezoid", "Scalene quadrilateral"),
    solution: "An equilateral parallelogram is called a rhombus."
  },
  {
    qrId: "g9e11",
    grade: 9,
    difficulty: 1,
    category: "linear-equations",
    title: "Y-Intercept of Line",
    questionType: "input",
    expectedAnswer: "(0, -9)",
    acceptableAnswers: ["(0, -9)", "(0,-9)", "-9", "0, -9"],
    problemText: "What is the y-intercept of the line y = -4x - 9?",
    answers: mc("(0, -9)", "(0, -4)", "(-9, 0)", "(0, 9)"),
    solution: "At x = 0, y = -9, so the y-intercept is (0, -9)."
  },
  {
    qrId: "g9e12",
    grade: 9,
    difficulty: 1,
    category: "linear-equations",
    title: "Slope through Origin",
    questionType: "input",
    expectedAnswer: "2",
    acceptableAnswers: ["2", "m = 2", "m=2"],
    problemText: "What is the slope of the line passing through origin (0, 0) and (4, 8)?",
    answers: mc("2", "1/2", "4", "8"),
    solution: "m = (8 - 0) / (4 - 0) = 8 / 4 = 2."
  },
  {
    qrId: "g9e13",
    grade: 9,
    difficulty: 1,
    category: "quadrilaterals-geometry",
    title: "Quadrilateral Interior Angles Sum",
    questionType: "input",
    expectedAnswer: "360°",
    acceptableAnswers: ["360", "360°", "360 deg", "360 degrees"],
    problemText: "What is the sum of all interior angles in any convex quadrilateral?",
    answers: mc("360°", "180°", "540°", "720°"),
    solution: "(4 - 2) × 180° = 2 × 180° = 360°."
  },
  {
    qrId: "g9e14",
    grade: 9,
    difficulty: 1,
    category: "linear-equations",
    title: "Y-Intercept of Proportional Line",
    questionType: "input",
    expectedAnswer: "(0, 0)",
    acceptableAnswers: ["(0, 0)", "(0,0)", "0,0", "0", "origin"],
    problemText: "In the equation y = 5x, what is the y-intercept?",
    answers: mc("(0, 0)", "(0, 5)", "(5, 0)", "None"),
    solution: "y = 5x + 0, so the line passes through the origin (0, 0)."
  },
  {
    qrId: "g9e15",
    grade: 9,
    difficulty: 1,
    category: "quadrilaterals-geometry",
    title: "Bisecting Diagonals Quadrilateral",
    questionType: "input",
    expectedAnswer: "Parallelogram",
    acceptableAnswers: ["parallelogram", "a parallelogram", "rectangle", "rhombus", "square"],
    problemText: "If the diagonals of a quadrilateral bisect each other, what type of quadrilateral must it be?",
    answers: mc("Parallelogram", "Trapezoid", "General Kite", "Cyclic polygon"),
    solution: "A quadrilateral whose diagonals bisect each other is a parallelogram."
  },

  // ==========================================
  // GRADE 9 AVERAGE (15 cards)
  // ==========================================
  {
    qrId: "g9a01",
    grade: 9,
    difficulty: 3,
    category: "linear-equations",
    title: "Slope Between Two Points",
    questionType: "input",
    expectedAnswer: "2",
    acceptableAnswers: ["2", "m = 2", "m=2"],
    problemText: "A line passes through (2, 3) and (6, 11). What is its slope?",
    answers: mc("2", "4", "1/2", "8"),
    solution: "m = (11 - 3) / (6 - 2) = 8 / 4 = 2."
  },
  {
    qrId: "g9a02",
    grade: 9,
    difficulty: 3,
    category: "linear-equations",
    title: "Evaluating Linear Function",
    questionType: "input",
    expectedAnswer: "4",
    acceptableAnswers: ["4", "f(5) = 4", "f(5)=4"],
    problemText: "In the linear function f(x) = 2x - 6, what is the value of f(5)?",
    answers: mc("4", "10", "-4", "6"),
    solution: "f(5) = 2(5) - 6 = 10 - 6 = 4."
  },
  {
    qrId: "g9a03",
    grade: 9,
    difficulty: 3,
    category: "linear-equations",
    title: "Tricycle Fare Model",
    questionType: "input",
    expectedAnswer: "F = 5x + 20",
    acceptableAnswers: ["F = 5x + 20", "F=5x+20", "5x+20", "5x + 20"],
    problemText: "A tricycle charges a ₱20 starting fare plus ₱5 for every additional kilometer. What equation represents the total fare F for x additional kilometers?",
    answers: mc("F = 5x + 20", "F = 20x + 5", "F = 25x", "F = 5x - 20"),
    solution: "Base fare = ₱20, rate = ₱5/km => Total Fare F = 5x + 20."
  },
  {
    qrId: "g9a04",
    grade: 9,
    difficulty: 3,
    category: "linear-equations",
    title: "Perpendicular Slope Calculation",
    questionType: "input",
    expectedAnswer: "-1/2",
    acceptableAnswers: ["-1/2", "-0.5", "- 1/2"],
    problemText: "A line has a slope of 2. What must be the slope of a line perpendicular to it?",
    answers: mc("-1/2", "2", "-2", "1/2"),
    solution: "Perpendicular lines have negative reciprocal slopes: m_perp = -1 / 2."
  },
  {
    qrId: "g9a05",
    grade: 9,
    difficulty: 3,
    category: "linear-equations",
    title: "Line Equation from Slope & Intercept",
    questionType: "input",
    expectedAnswer: "y = -2x + 3",
    acceptableAnswers: ["y = -2x + 3", "y=-2x+3", "-2x + 3", "-2x+3"],
    problemText: "A line passes through (0, 3) and has slope -2. What equation represents the line?",
    answers: mc("y = -2x + 3", "y = 2x + 3", "y = -2x - 3", "y = 3x - 2"),
    solution: "Using y = mx + b with m = -2 and b = 3: y = -2x + 3."
  },
  {
    qrId: "g9a06",
    grade: 9,
    difficulty: 3,
    category: "quadrilaterals-geometry",
    title: "Congruent Diagonals Parallelogram",
    questionType: "input",
    expectedAnswer: "Rectangle",
    acceptableAnswers: ["rectangle", "square", "rectangle or square"],
    problemText: "What kind of parallelogram has congruent diagonals?",
    answers: mc("Rectangle", "Rhombus", "Parallelogram", "Trapezoid"),
    solution: "A parallelogram has equal-length diagonals if and only if it is a rectangle."
  },
  {
    qrId: "g9a07",
    grade: 9,
    difficulty: 3,
    category: "quadrilaterals-geometry",
    title: "Opposite Side Length in Parallelogram",
    questionType: "input",
    expectedAnswer: "14 cm",
    acceptableAnswers: ["14", "14 cm", "14cm"],
    problemText: "In parallelogram ABCD, AB = 14 cm. What is the length of CD?",
    answers: mc("14 cm", "7 cm", "28 cm", "Cannot be determined"),
    solution: "Opposite sides of a parallelogram are congruent: CD = AB = 14 cm."
  },
  {
    qrId: "g9a08",
    grade: 9,
    difficulty: 3,
    category: "quadrilaterals-geometry",
    title: "Rectangle Area Calculation",
    questionType: "input",
    expectedAnswer: "35 cm²",
    acceptableAnswers: ["35", "35 cm²", "35cm²", "35 sq cm", "35 cm^2"],
    problemText: "What is the area of a rectangle whose sides are 5 cm and 7 cm?",
    answers: mc("35 cm²", "24 cm²", "12 cm²", "70 cm²"),
    solution: "Area = length × width = 5 cm × 7 cm = 35 cm²."
  },
  {
    qrId: "g9a09",
    grade: 9,
    difficulty: 3,
    category: "linear-equations",
    title: "Parallel Lines Slope Value",
    questionType: "input",
    expectedAnswer: "4",
    acceptableAnswers: ["4", "m = 4", "m=4"],
    problemText: "Two lines have slopes 4 and m. If they are parallel, what is the value of m?",
    answers: mc("4", "-4", "1/4", "-1/4"),
    solution: "Parallel lines have identical slopes, so m = 4."
  },
  {
    qrId: "g9a10",
    grade: 9,
    difficulty: 3,
    category: "linear-equations",
    title: "Slope Identification",
    questionType: "input",
    expectedAnswer: "3",
    acceptableAnswers: ["3", "m = 3", "m=3"],
    problemText: "In the equation y = 3x - 2, what is the slope?",
    answers: mc("3", "-2", "2", "-3"),
    solution: "In y = mx + b, slope m is the coefficient of x: m = 3."
  },
  {
    qrId: "g9a11",
    grade: 9,
    difficulty: 3,
    category: "linear-equations",
    title: "Interpreting Linear Constant",
    questionType: "input",
    expectedAnswer: "Fixed starting fare",
    acceptableAnswers: ["fixed starting fare", "starting fare", "base fare", "initial fare", "fixed fare"],
    problemText: "A taxi fare is modeled by F = 10d + 50, where d is the distance in kilometers. What does the constant 50 represent?",
    answers: mc("Fixed starting fare", "Fare per kilometer", "Total distance", "Maximum passenger count"),
    solution: "When distance d = 0, F = 50. The constant represents the initial fixed base fare."
  },
  {
    qrId: "g9a12",
    grade: 9,
    difficulty: 3,
    category: "linear-equations",
    title: "Identifying Perpendicular Slopes",
    questionType: "input",
    expectedAnswer: "Perpendicular lines",
    acceptableAnswers: ["perpendicular", "perpendicular lines"],
    problemText: "Two lines have slopes 4 and -1/4. What geometric relationship do the two lines have?",
    answers: mc("Perpendicular lines", "Parallel lines", "Intersecting at 45°", "Coincident lines"),
    solution: "Product of slopes = 4 × (-1/4) = -1, which defines perpendicular lines."
  },
  {
    qrId: "g9a13",
    grade: 9,
    difficulty: 3,
    category: "linear-equations",
    title: "Lines with Equal Slopes",
    questionType: "input",
    expectedAnswer: "Parallel lines",
    acceptableAnswers: ["parallel", "parallel lines"],
    problemText: "Two lines have the same slopes equal to 2. What relationship do the two lines have?",
    answers: mc("Parallel lines", "Perpendicular lines", "Intersecting lines", "Skew lines"),
    solution: "Lines with equal slopes in the same plane are parallel."
  },
  {
    qrId: "g9a14",
    grade: 9,
    difficulty: 3,
    category: "quadrilaterals-geometry",
    title: "Square Flower Bed Area",
    questionType: "input",
    expectedAnswer: "36 m²",
    acceptableAnswers: ["36", "36 m²", "36m²", "36 sq m", "36 m^2"],
    problemText: "A rectangular school garden measures 18 m by 10 m. A square flower bed with side lengths of 6 m is placed inside the garden. What is the area of the flower bed?",
    answers: mc("36 m²", "180 m²", "24 m²", "144 m²"),
    solution: "Area of square = side² = 6 m × 6 m = 36 m²."
  },
  {
    qrId: "g9a15",
    grade: 9,
    difficulty: 3,
    category: "quadrilaterals-geometry",
    title: "Parallelogram Proof Property",
    questionType: "multiple_choice",
    expectedAnswer: "Both pairs of opposite sides are congruent.",
    acceptableAnswers: ["both pairs of opposite sides are congruent.", "opposite sides are congruent"],
    problemText: "Quadrilateral ABCD has sides given. What property shows that it is a parallelogram?",
    answers: mc("Both pairs of opposite sides are congruent.", "One pair of adjacent sides is equal.", "The diagonals are perpendicular.", "One angle is a right angle."),
    solution: "A quadrilateral is a parallelogram if and only if both pairs of opposite sides are congruent."
  },

  // ==========================================
  // GRADE 9 DIFFICULT (6 cards)
  // ==========================================
  {
    qrId: "g9d01",
    grade: 9,
    difficulty: 5,
    category: "linear-equations",
    title: "Parallel Slopes Reasoning",
    questionType: "input",
    expectedAnswer: "Student A",
    acceptableAnswers: ["student a", "a", "student a is correct"],
    problemText: "Students claim:\nStudent A: Two lines are parallel because they both have a slope of 3.\nStudent B: Two lines are perpendicular because they both have a slope of 3.\nWhich student is correct?",
    answers: mc("Student A", "Student B", "Both are correct", "Neither is correct"),
    solution: "Equal slopes mean parallel lines, so Student A is correct."
  },
  {
    qrId: "g9d02",
    grade: 9,
    difficulty: 5,
    category: "quadrilaterals-geometry",
    title: "Fence Perimeter Calculation",
    questionType: "input",
    expectedAnswer: "36 m",
    acceptableAnswers: ["36", "36 m", "36m", "36 meters"],
    problemText: "A rectangular fence has measurements of 10 m and 8 m on the sides. What is its perimeter?",
    answers: mc("36 m", "80 m", "18 m", "40 m"),
    solution: "Perimeter = 2(length + width) = 2(10 + 8) = 2(18) = 36 m."
  },
  {
    qrId: "g9d03",
    grade: 9,
    difficulty: 5,
    category: "quadrilaterals-geometry",
    title: "Vegetable Garden Dimensions",
    questionType: "input",
    expectedAnswer: "15 m by 8 m",
    acceptableAnswers: ["15 m by 8 m", "15 by 8", "15x8", "15m by 8m", "15, 8", "12 by 10", "20 by 6", "24 by 5", "30 by 4", "40 by 3", "60 by 2", "120 by 1"],
    problemText: "Grade 9 students want to create a rectangular vegetable garden with an area of exactly 120 m² and length greater than width. Give a possible dimension pair (Length × Width).",
    answers: mc("15 m by 8 m", "10 m by 12 m", "14 m by 9 m", "25 m by 5 m"),
    solution: "Possible factor pairs where Length > Width: 15m × 8m, 12m × 10m, 20m × 6m, 24m × 5m, 30m × 4m, 40m × 3m, 60m × 2m, 120m × 1m."
  },
  {
    qrId: "g9d04",
    grade: 9,
    difficulty: 5,
    category: "linear-equations",
    title: "Bridge Boundary Slopes",
    questionType: "input",
    expectedAnswer: "Both slopes are 2",
    acceptableAnswers: ["both 2", "2", "both slopes are 2", "slope 2", "both have a slope of 2"],
    problemText: "Two bridge boundaries are represented by lines:\nBoundary A: y = 2x + 3\nBoundary B: y - 2x = 10\nWhat is the slope of Boundary A and Boundary B?",
    answers: mc("Both have a slope of 2", "Slope A = 2, Slope B = -2", "Slope A = 3, Slope B = 10", "Slope A = 2, Slope B = 10"),
    solution: "Boundary A has m = 2. Boundary B is y = 2x + 10, which also has m = 2."
  },
  {
    qrId: "g9d05",
    grade: 9,
    difficulty: 5,
    category: "quadrilaterals-geometry",
    title: "Picnic Platform Flooring Area",
    questionType: "input",
    expectedAnswer: "114 m²",
    acceptableAnswers: ["114", "114 m²", "114m²", "114 sq m", "114 m^2"],
    problemText: "A public park picnic platform is a rectangle measuring 15 m by 10 m. Inside is a decorative square stone area with 6 m sides. What is the area outside the square to be covered with outdoor flooring?",
    answers: mc("114 m²", "150 m²", "36 m²", "126 m²"),
    solution: "Platform area = 15 × 10 = 150 m². Square stone area = 6 × 6 = 36 m². Flooring area = 150 - 36 = 114 m²."
  },
  {
    qrId: "g9d06",
    grade: 9,
    difficulty: 5,
    category: "quadrilaterals-geometry",
    title: "Border Material Sufficiency",
    questionType: "input",
    expectedAnswer: "Yes, perimeter is 24 m",
    acceptableAnswers: ["yes", "yes, 24m", "yes, perimeter is 24m", "yes, because the perimeter of the square is only 24m"],
    problemText: "A square stone area has 6 m sides. Organizers have 25 meters of border material. Is this enough border material? Why?",
    answers: mc("Yes, because the perimeter of the square is only 24 m.", "No, because the perimeter is 36 m.", "No, because the perimeter is 26 m.", "Yes, because the area is 24 m²."),
    solution: "Perimeter of the square = 4 × 6 m = 24 m. Since 25 m > 24 m, the material is enough."
  },

  // ==========================================
  // GRADE 10 EASY (11 cards)
  // ==========================================
  {
    qrId: "g10e01",
    grade: 10,
    difficulty: 1,
    category: "trigonometry",
    title: "DMS to Decimal Degrees",
    questionType: "input",
    expectedAnswer: "45.50°",
    acceptableAnswers: ["45.50", "45.5", "45.50°", "45.5°", "45.50 degrees"],
    problemText: "Convert the angle measure 45° 30' into decimal degrees.",
    answers: mc("45.50°", "45.30°", "45.05°", "45.60°"),
    solution: "30' = 30 / 60 = 0.50°. Therefore 45° 30' = 45.50°."
  },
  {
    qrId: "g10e02",
    grade: 10,
    difficulty: 1,
    category: "trigonometry",
    title: "Decimal Degrees to DMS",
    questionType: "input",
    expectedAnswer: "12° 04' 48''",
    acceptableAnswers: ["12° 04' 48''", "12° 4' 48''", "12° 4' 48\"", "12° 04' 48\""],
    problemText: "Which degree, minute, and seconds value is equal to the angle measure 12.08°?",
    answers: mc("12° 04' 48''", "12° 08' 00''", "12° 48' 04''", "12° 00' 48''"),
    solution: "0.08° × 60 = 4.8' (4 minutes); 0.8' × 60 = 48''. Thus 12.08° = 12° 04' 48''."
  },
  {
    qrId: "g10e03",
    grade: 10,
    difficulty: 1,
    category: "trigonometry",
    title: "Mt. Isarog Field Triangle Classification",
    questionType: "input",
    expectedAnswer: "Right triangle",
    acceptableAnswers: ["right triangle", "right", "a right triangle"],
    problemText: "A triangular field near Mt. Isarog has sides 30 m, 40 m, and 50 m. What type of triangle is it?",
    answers: mc("Right triangle", "Acute triangle", "Obtuse triangle", "Equilateral triangle"),
    solution: "30² + 40² = 900 + 1600 = 2500 = 50². By Pythagorean Theorem, it is a right triangle."
  },
  {
    qrId: "g10e04",
    grade: 10,
    difficulty: 1,
    category: "trigonometry",
    title: "Obtuse Triangle Classification",
    questionType: "input",
    expectedAnswer: "Obtuse triangle",
    acceptableAnswers: ["obtuse", "obtuse triangle", "an obtuse triangle"],
    problemText: "The largest angle of an oblique triangle measures 110°. The triangle is classified as:",
    answers: mc("Obtuse triangle", "Acute triangle", "Right triangle", "Equiangular triangle"),
    solution: "Any triangle with an interior angle greater than 90° is an obtuse triangle."
  },
  {
    qrId: "g10e05",
    grade: 10,
    difficulty: 1,
    category: "trigonometry",
    title: "Acute Triangle Classification",
    questionType: "input",
    expectedAnswer: "Acute triangle",
    acceptableAnswers: ["acute", "acute triangle", "an acute triangle"],
    problemText: "If all three angles of a triangle are less than 90°, the triangle is classified as:",
    answers: mc("Acute triangle", "Obtuse triangle", "Right triangle", "Reflex triangle"),
    solution: "A triangle in which all three angles measure less than 90° is an acute triangle."
  },
  {
    qrId: "g10e06",
    grade: 10,
    difficulty: 1,
    category: "trigonometry",
    title: "Types of Oblique Triangles",
    questionType: "multiple_choice",
    expectedAnswer: "Acute and obtuse triangles",
    acceptableAnswers: ["acute and obtuse", "acute and obtuse triangles"],
    problemText: "An oblique triangle (a triangle with no 90° angle) is classified according to its angles as:",
    answers: mc("Acute and obtuse triangles", "Right and scalene triangles", "Equilateral and isosceles only", "Convex and concave"),
    solution: "Non-right (oblique) triangles are either acute (all angles < 90°) or obtuse (one angle > 90°)."
  },
  {
    qrId: "g10e07",
    grade: 10,
    difficulty: 1,
    category: "law-of-sines-cosines",
    title: "Law of Sines Equation",
    questionType: "multiple_choice",
    expectedAnswer: "a/sin(A) = b/sin(B) = c/sin(C)",
    acceptableAnswers: ["a/sin(A)=b/sin(B)=c/sin(C)", "a/sinA=b/sinB=c/sinC"],
    problemText: "What formula represents the Law of Sines?",
    answers: mc("a / sin(A) = b / sin(B) = c / sin(C)", "a² = b² + c² - 2bc cos(A)", "sin(A) + sin(B) = sin(C)", "a cos(A) = b cos(B)"),
    solution: "The Law of Sines states: a / sin(A) = b / sin(B) = c / sin(C)."
  },
  {
    qrId: "g10e08",
    grade: 10,
    difficulty: 1,
    category: "law-of-sines-cosines",
    title: "Law of Cosines Equation",
    questionType: "multiple_choice",
    expectedAnswer: "a² = b² + c² - 2bc cos(A)",
    acceptableAnswers: ["a²=b²+c²-2bccos(A)", "a^2 = b^2 + c^2 - 2bc cos(A)", "a^2=b^2+c^2-2bc*cos(A)"],
    problemText: "What formula represents the Law of Cosines?",
    answers: mc("a² = b² + c² - 2bc cos(A)", "a² = b² + c² + 2bc cos(A)", "a = b cos(C) + c cos(B)", "a² = b² + c² - 2bc sin(A)"),
    solution: "The Law of Cosines is a² = b² + c² - 2bc cos(A)."
  },
  {
    qrId: "g10e09",
    grade: 10,
    difficulty: 1,
    category: "law-of-sines-cosines",
    title: "Triangular Garden in Naga City",
    questionType: "input",
    expectedAnswer: "Law of Cosines",
    acceptableAnswers: ["law of cosines", "cosines", "the law of cosines"],
    problemText: "A triangular garden in Naga City has two sides measuring 12 m and 15 m with an included angle of 70°. Which law should be used to find the third side?",
    answers: mc("Law of Cosines", "Law of Sines", "Pythagorean Theorem", "Tangent Ratio"),
    solution: "When given two sides and the included angle (SAS), the Law of Cosines is used."
  },
  {
    qrId: "g10e10",
    grade: 10,
    difficulty: 1,
    category: "trigonometry",
    title: "Included Angle Identification",
    questionType: "input",
    expectedAnswer: "∠C",
    acceptableAnswers: ["∠C", "C", "angle C", "angle c", "<C"],
    problemText: "In triangle ABC, the sides AC and BC meet at vertex C. What is the included angle between AC and BC?",
    answers: mc("∠C", "∠A", "∠B", "∠ABC"),
    solution: "The angle formed between sides AC and BC sharing vertex C is ∠C."
  },
  {
    qrId: "g10e11",
    grade: 10,
    difficulty: 1,
    category: "law-of-sines-cosines",
    title: "Naga City Rescue Route Measurement",
    questionType: "input",
    expectedAnswer: "Law of Cosines",
    acceptableAnswers: ["law of cosines", "cosines", "the law of cosines"],
    problemText: "A rescue team in Naga City needs to determine the distance between two locations. They know two sides of a triangular route and the angle between them. Which method is most appropriate?",
    answers: mc("Law of Cosines", "Law of Sines", "Pythagorean Theorem", "Right triangle trigonometry"),
    solution: "Given two sides and the included angle (SAS), the Law of Cosines is appropriate."
  },

  // ==========================================
  // GRADE 10 AVERAGE (6 cards)
  // ==========================================
  {
    qrId: "g10a01",
    grade: 10,
    difficulty: 3,
    category: "trigonometry",
    title: "Flagpole Height Elevation",
    questionType: "input",
    expectedAnswer: "15 meters",
    acceptableAnswers: ["15", "15 m", "15 meters", "15m"],
    problemText: "An observer stands exactly 15 meters away from the base of a vertical flagpole. The angle of elevation from the observer’s feet to the top of the flagpole is 45°. How tall is the flagpole?",
    answers: mc("15 meters", "30 meters", "15√2 meters", "10 meters"),
    solution: "tan(45°) = height / distance => 1 = h / 15 => h = 15 meters."
  },
  {
    qrId: "g10a02",
    grade: 10,
    difficulty: 3,
    category: "trigonometry",
    title: "Third Angle in Triangle",
    questionType: "input",
    expectedAnswer: "75°",
    acceptableAnswers: ["75", "75°", "75 deg", "75 degrees"],
    problemText: "In triangle ABC, ∠A = 45° and ∠C = 60°. What is the measure of ∠B?",
    answers: mc("75°", "85°", "65°", "95°"),
    solution: "Sum of angles in a triangle is 180°: ∠B = 180° - 45° - 60° = 75°."
  },
  {
    qrId: "g10a03",
    grade: 10,
    difficulty: 3,
    category: "law-of-sines-cosines",
    title: "Catanduanes Fisherman Law of Sines",
    questionType: "multiple_choice",
    expectedAnswer: "At least one known side and its opposite angle",
    acceptableAnswers: ["at least one known side and its opposite angle", "one known side and its opposite angle"],
    problemText: "A fisherman in the waters near Catanduanes observes two landmarks 20 km apart with angles 45° and 65°. What information is needed to solve for an unknown side using the Law of Sines?",
    answers: mc("At least one known side and its opposite angle", "All three side lengths", "Two sides and the included angle only", "The area and perimeter"),
    solution: "The Law of Sines requires at least one side and its corresponding opposite angle pair."
  },
  {
    qrId: "g10a04",
    grade: 10,
    difficulty: 3,
    category: "law-of-sines-cosines",
    title: "Law of Sines Side Length",
    questionType: "input",
    expectedAnswer: "4.24 cm",
    acceptableAnswers: ["4.24", "4.24 cm", "4.24cm", "4.2"],
    problemText: "In triangle ABC, ∠A = 25°, ∠B = 85°, and AC = 10 cm. Using BC = (10 sin 25°) / sin 85°, what is the approximate length of BC?",
    answers: mc("4.24 cm", "5.12 cm", "3.85 cm", "6.20 cm"),
    solution: "BC = 10 * sin(25°) / sin(85°) ≈ 10 * 0.4226 / 0.9962 ≈ 4.24 cm."
  },
  {
    qrId: "g10a05",
    grade: 10,
    difficulty: 3,
    category: "trigonometry",
    title: "Pasacao Boat Navigation Angle",
    questionType: "input",
    expectedAnswer: "70°",
    acceptableAnswers: ["70", "70°", "70 deg", "70 degrees"],
    problemText: "A boat travels from Pasacao toward a point offshore. If two observed angles are 40° and 70°, what is the third angle of the triangle?",
    answers: mc("70°", "80°", "60°", "50°"),
    solution: "180° - 40° - 70° = 70°."
  },
  {
    qrId: "g10a06",
    grade: 10,
    difficulty: 3,
    category: "law-of-sines-cosines",
    title: "Law of Cosines Formulation",
    questionType: "multiple_choice",
    expectedAnswer: "e² = 10² + 12² - 2(10)(12)cos(60°)",
    acceptableAnswers: ["e²=10²+12²-2(10)(12)cos60°", "e^2 = 10^2 + 12^2 - 2(10)(12)cos(60)"],
    problemText: "In triangle DEF, side d = 10 cm, side f = 12 cm, and ∠E = 60°. Which equation correctly determines side e?",
    answers: mc("e² = 10² + 12² - 2(10)(12)cos(60°)", "e² = 10² + 12² + 2(10)(12)cos(60°)", "e = 10sin(60°) + 12cos(60°)", "e² = 10² + 12² - 2(10)(12)sin(60°)"),
    solution: "By Law of Cosines for side e opposite ∠E: e² = d² + f² - 2df cos(E) = 10² + 12² - 2(10)(12)cos(60°)."
  },

  // ==========================================
  // GRADE 10 DIFFICULT (6 cards)
  // ==========================================
  {
    qrId: "g10d01",
    grade: 10,
    difficulty: 5,
    category: "law-of-sines-cosines",
    title: "Triangle Angle via Law of Sines",
    questionType: "input",
    expectedAnswer: "35° 22' 08''",
    acceptableAnswers: ["35° 22' 08''", "35° 22' 08\"", "35.37°", "35.37", "35° 22'"],
    problemText: "Determine the measure of ∠C in triangle ABC if AB = 0.77 km, m∠A = 110°, and BC = 1.25 km.",
    answers: mc("35° 22' 08''", "45° 15' 30''", "28° 40' 12''", "30° 00' 00''"),
    solution: "sin(C) / 0.77 = sin(110°) / 1.25 => sin(C) = 0.77 * sin(110°) / 1.25 ≈ 0.5788 => ∠C ≈ 35.3688° ≈ 35° 22' 08''."
  },
  {
    qrId: "g10d02",
    grade: 10,
    difficulty: 5,
    category: "law-of-sines-cosines",
    title: "Triangular Lot Third Side",
    questionType: "input",
    expectedAnswer: "12.49 m",
    acceptableAnswers: ["12.49", "12.49 m", "12.49m", "12.5", "12.5 m"],
    problemText: "A triangular lot has sides 10 m and 14 m with an included angle of 60°. What is the approximate length of the third side?",
    answers: mc("12.49 m", "15.20 m", "11.18 m", "14.00 m"),
    solution: "c² = 10² + 14² - 2(10)(14)cos(60°) = 100 + 196 - 140 = 156 => c = √156 ≈ 12.49 m."
  },
  {
    qrId: "g10d03",
    grade: 10,
    difficulty: 5,
    category: "law-of-sines-cosines",
    title: "Surveyor Triangular Area Third Side",
    questionType: "input",
    expectedAnswer: "21.25 m",
    acceptableAnswers: ["21.25", "21.25 m", "21.25m", "21.3"],
    problemText: "A surveyor measures two sides of a triangular area as 20 m and 30 m and the included angle as 45°. What is the approximate third side?",
    answers: mc("21.25 m", "25.50 m", "18.75 m", "28.10 m"),
    solution: "c² = 20² + 30² - 2(20)(30)cos(45°) = 400 + 900 - 1200(0.7071) = 1300 - 848.53 = 451.47 => c = √451.47 ≈ 21.25 m."
  },
  {
    qrId: "g10d04",
    grade: 10,
    difficulty: 5,
    category: "law-of-sines-cosines",
    title: "Angle Measure from Law of Cosines",
    questionType: "input",
    expectedAnswer: "55° 46' 16''",
    acceptableAnswers: ["55° 46' 16''", "55° 46' 16\"", "55.77°", "55.77", "55° 46'"],
    problemText: "What is m∠E in the equation 10² = 8² + 12² - 2(8)(12)cos(E)?",
    answers: mc("55° 46' 16''", "62° 30' 00''", "48° 20' 15''", "50° 12' 40''"),
    solution: "100 = 64 + 144 - 192 cos(E) => 100 = 208 - 192 cos(E) => -108 = -192 cos(E) => cos(E) = 0.5625 => E ≈ 55.7711° ≈ 55° 46' 16''."
  },
  {
    qrId: "g10d05",
    grade: 10,
    difficulty: 5,
    category: "law-of-sines-cosines",
    title: "Law of Sines Side Computation",
    questionType: "input",
    expectedAnswer: "13.66 cm",
    acceptableAnswers: ["13.66", "13.66 cm", "13.66cm", "13.7"],
    problemText: "In triangle ABC, ∠A = 45°, ∠B = 75°, and side a = 10 cm. Using the Law of Sines, approximately how long is side b?",
    answers: mc("13.66 cm", "11.50 cm", "15.20 cm", "12.00 cm"),
    solution: "b = a * sin(B) / sin(A) = 10 * sin(75°) / sin(45°) ≈ 10 * 0.9659 / 0.7071 ≈ 13.66 cm."
  },
  {
    qrId: "g10d06",
    grade: 10,
    difficulty: 5,
    category: "law-of-sines-cosines",
    title: "Triangle PQR Side Length",
    questionType: "input",
    expectedAnswer: "6.06 cm",
    acceptableAnswers: ["6.06", "6.06 cm", "6.06cm", "6.1"],
    problemText: "In triangle PQR, ∠P = 30°, ∠Q = 52°, and side r = 12 cm. What is the approximate length of side p?",
    answers: mc("6.06 cm", "7.45 cm", "5.12 cm", "8.20 cm"),
    solution: "∠R = 180° - 30° - 52° = 98°. p = r * sin(P) / sin(R) = 12 * sin(30°) / sin(98°) ≈ 12 * 0.5 / 0.9903 ≈ 6.06 cm."
  }
];

const finalOutput = {
  cards: cards.map(c => ({
    ...c,
    answers: c.questionType === 'input' ? [] : c.answers,
    imageRes: {
      g7e02: '/images/gr7e2fig.png',
      g7d02: '/images/gr7d2fig.png',
      g7d03: '/images/gr7d3fig.png',
      g7d10: '/images/gr7d10fig.png',
      g9e03: '/images/gr9e3fig.png',
      g9a15: '/images/gr9a15fig.png',
      g9f04: '/images/gr9fc4fig.png',
      g10f02: '/images/gr10fc2fig.png',
      g10f03: '/images/gr10fc3fig.png',
      g10f04: '/images/gr10fc4fig.png',
      g10f05: '/images/gr10fc5fig.png',
    }[c.qrId] || null,
    ...(c.qrId === 'g7d09' ? {
      answers: c.answers.map((answer, index) => ({
        ...answer,
        imageRes: `/images/gr7d9mc-${String.fromCharCode(97 + index)}.png`,
      })),
    } : {}),
  }))
};

console.log(`Generated ${finalOutput.cards.length} cards!`);
fs.writeFileSync('lihyara_all_cards.json', JSON.stringify(finalOutput, null, 2), 'utf8');
fs.writeFileSync('public/lihyara_all_cards.json', JSON.stringify(finalOutput, null, 2), 'utf8');
fs.writeFileSync('src/data/cards.json', JSON.stringify(finalOutput, null, 2), 'utf8');
console.log('Saved to root, public, and src/data!');
